Mentor/urls.py
from django.urls import path
from . import views
from .views import MentorListCreateView, MentorDetailView, MentorRegisterView, MentorLoginView, MentorDetailsView

app_name = 'Mentor'

urlpatterns = [
    
    path('mentor/mentors/', MentorListCreateView.as_view(), name='mentor-list'),
    path('mentor/mentors/<int:pk>/', MentorDetailView.as_view(), name='mentor-detail'),
    path('mentor/register/', MentorRegisterView.as_view(), name='mentor-registration'),
    path('mentor/login/', MentorLoginView.as_view(), name='login'),
    path('mentor/user-details/', MentorDetailsView.as_view(), name='user-details'),
    path('', views.home, name='home'),
    path('mentor/edit-profile/', views.edit_profile, name='edit-profile'),
    path('mentor/upload/', views.upload_video, name='upload_video'),
    path('mentor/view-videos/', views.view_videos, name='view_videos'),
    path('mentor/mentor-dashboard/', views.mentor_dashboard, name='mentor-dashboard'),

    # path('registration/', views.mentor_registration, name='mentor-registration'),
    # path('login/', views.mentor_login, name='mentor-login'),
]

School/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.contrib.staticfiles.urls import static, staticfiles_urlpatterns
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Mentor.urls')),
    path('student/', include('Student.urls')),
    path('', views.home, name='home'),
    # path('', views.home, name='home' ),
]
urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Mentor/models.py
from django.db import models

class Mentor(models.Model):
    GENDER_CHOICES = (
        ('M', 'Male'),
        ('F', 'Female'),
        ('O', 'Other'),
    )

    username = models.CharField(max_length=100)
    mobile = models.CharField(max_length=15, unique=True)
    full_name = models.CharField(max_length=255)
    email = models.EmailField()
    password = models.CharField(max_length=100)
    gender = models.CharField(max_length=1, choices=GENDER_CHOICES)
    address = models.TextField()
    aadhar = models.CharField(max_length=20)
    pic = models.ImageField(upload_to='mentor_pics/')
    class_field = models.CharField(max_length=50)
    section = models.CharField(max_length=10)



class Video(models.Model):
    title = models.CharField(max_length=100)
    video_file = models.FileField(upload_to='videos/')
    uploaded_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title

Mentor/forms.py
from django import forms
from .models import Mentor
from .models import Video

class MentorEditForm(forms.ModelForm):
    class Meta:
        model = Mentor
        fields = ['username', 'mobile', 'full_name', 'email', 'password', 'gender', 'address', 'aadhar', 'pic', 'class_field', 'section']
        # Customize the fields as needed

class VideoForm(forms.ModelForm):
    class Meta:
        model = Video
        fields = ['title', 'video_file']

Mentor/views.py
from rest_framework import generics
from .models import Mentor
from .serializers import MentorSerializer

from rest_framework import generics, status
from rest_framework.response import Response
from rest_framework.authtoken.models import Token
from django.contrib.auth import authenticate


from django.http import HttpResponse
from django.views import View

from django.contrib.auth.decorators import login_required
from .forms import MentorEditForm

from django.shortcuts import render, redirect
from .forms import VideoForm

from .models import Video


class MentorListCreateView(generics.ListCreateAPIView):
    queryset = Mentor.objects.all()
    serializer_class = MentorSerializer

class MentorDetailView(generics.RetrieveUpdateDestroyAPIView):
    queryset = Mentor.objects.all()
    serializer_class = MentorSerializer


class MentorRegisterView(generics.CreateAPIView):
    queryset = Mentor.objects.all()
    serializer_class = MentorSerializer

    def get(self, request, *args, **kwargs):
        return render(request, 'registration.html')

    def post(self, request, *args, **kwargs):
        serializer = self.get_serializer(data=request.data)
        if serializer.is_valid():
            serializer.save()
            return Response({
                "status": status.HTTP_201_CREATED,
                "message": "User registered successfully.",
            }, status=status.HTTP_201_CREATED)
        return Response({
            "status": status.HTTP_400_BAD_REQUEST,
            "message": serializer.errors.get('message', 'Invalid input data.'),
            "data": serializer.errors
        }, status=status.HTTP_400_BAD_REQUEST)



class MentorLoginView(View):
    def get(self, request, *args, **kwargs):
        return render(request, 'login.html')

    def post(self, request, *args, **kwargs):
        username_mobile = request.POST.get('username_mobile')
        password = request.POST.get('password')

        # Authenticate user by username or mobile number
        user = authenticate(request, username=username_mobile, password=password)
        if user is not None:
            # User authentication successful, generate token
            token, created = Token.objects.get_or_create(user=user)
            # return redirect('mentor-dashboard')
            return Response({'token': token.key}, status=status.HTTP_200_OK)
        else:
            # Invalid credentials
            return Response({'error': 'Invalid credentials'}, status=status.HTTP_401_UNAUTHORIZED)


class MentorDetailsView(generics.RetrieveAPIView):
    serializer_class = MentorSerializer

    def get_object(self):
        token = self.request.GET.get('token')
        if token:
            try:
                user = Token.objects.get(key=token).user
                return user
            except Token.DoesNotExist:
                return None
        return None

    def get(self, request, *args, **kwargs):
        user = self.get_object()
        if user:
            serializer = self.serializer_class(user)
            return Response(serializer.data, status=status.HTTP_200_OK)
        else:
            return Response({'error': 'Invalid token'}, status=status.HTTP_401_UNAUTHORIZED)
        
@login_required
def edit_profile(request):
    if request.method == 'POST':
        form = MentorEditForm(request.POST, request.FILES, instance=request.user)
        if form.is_valid():
            form.save()
            return redirect('user-details')  # Redirect to the user details page after successful update
    else:
        form = MentorEditForm(instance=request.user)
    
    return render(request, 'edit_profile.html', {'form': form})

@login_required
def upload_video(request):
    if request.method == 'POST':
        form = VideoForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return redirect('success_page')  # Redirect to a success page after upload
    else:
        form = VideoForm()
    return render(request, 'upload_video.html', {'form': form})

@login_required
def view_videos(request):
    videos = Video.objects.all()
    return render(request, 'view_videos.html', {'videos': videos})


def home(request):
    return render(request, 'home.html')

def mentor_registration(request):
    return render(request, 'Mentor:mentor-registration')

@login_required
def mentor_dashboard(request):
    return render(request, 'mentor_dashboard.html')

Mentor/templates/base.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>
      {% block title %}
          Blogs Page
      {% endblock %}
    </title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">

  
  </head>
  <body>
    <nav class="navbar navbar-expand-sm bg-dark navbar-dark">

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'index' %}">Home</a>
        </li>

        {% if user.is_authenticated %}

        <li class="nav-item">
          <a class="nav-link" href="{% url 'App_Login:logout' %}">Logout</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'App_Login:profile' %}">Profile</a>
        </li>
        
        <li class="nav-item">
          <a class="nav-link" href="{% url 'App_Blog:create_blog' %}">Write Blog</a>
        </li>



        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            {{ user.username }}
          </a>
          <ul class="dropdown-menu">
            <li><a class="dropdown-item" href="{% url 'App_Blog:my_blogs' %}">My Blogs</a></li>
            <li><a class="dropdown-item" href="{% url 'App_Login:profile' %}">Your Profile</a></li>
            <li><a class="dropdown-item" href="{% url 'App_Login:logout' %}">Logout</a></li>
          </ul>
        </li>
      </ul>
      {% else %}

      <li class="nav-item">
        <a class="nav-link" href="{% url 'App_Login:signup' %}">Sign Up</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'App_Login:signin' %}">Login</a>
      </li>
      {% endif %}
  </div>
</nav>

<div class="container" style="padding-top:20px">
  {% block body_block %}

  {% endblock %}
</div>


    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz" crossorigin="anonymous"></script>
  </body>
</html>

Mentor/templates/edit_profile.html
<!-- edit_profile.html -->

<!DOCTYPE html>
<html>
<head>
    <title>Edit Profile</title>
    <!-- Add your CSS link here -->
</head>
<body>
    <h1>Edit Profile</h1>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Save Changes">
    </form>
</body>
</html>

Mentor/templates/home.html
<!DOCTYPE html>
<html>
<head>
    <title>Home</title>
    <!-- Add your CSS link here -->
</head>
<body>
    <h1>Welcome</h1>
    <div>
        <h2>Mentor Actions:</h2>
        <button onclick="location.href='/mentor/register/'">Mentor Register</button>
        <button onclick="location.href='/mentor/login/'">Mentor Login</button>
    </div>
    <div>
        <h2>Student Actions:</h2>
        <button onclick="location.href='/student/register/'">Student Register</button>
        <button onclick="location.href='/student/login/'">Student Login</button>
    </div>
</body>
</html>

Mentor/templates/login.html
<!DOCTYPE html>
<html>
<head>
    <title>Mentor Login</title>
    <!-- Add your CSS link here -->
</head>
<body>
    <h1>Mentor Login</h1>
    <!-- Form for mentor login -->
        <form method="post" action="{% url 'Mentor:login' %}"> 
        {% csrf_token %}
        
        <!-- Username or Mobile -->
        <label for="username_mobile">Username/Mobile:</label><br>
        <input type="text" id="username_mobile" name="username_mobile" required><br><br>
        
        <!-- Password -->
        <label for="password">Password:</label><br>
        <input type="password" id="password" name="password" required><br><br>
        
        <!-- Submit Button -->
        <input type="submit" value="Login">
    </form>
</body>
</html>
 

Mentor/templates/mentor_dashboard.html
<!DOCTYPE html>
<html>
<head>
    <title>Mentor Dashboard</title>
    <!-- Add your CSS link here -->
</head>
<body>
    <h1>Welcome to Mentor Dashboard</h1>
    <div>
        <p>Click on the buttons below to navigate:</p>
        <a href="{% url 'Mentor:user-details' %}">
            <button>Mentor Details</button>
        </a>
        <a href="{% url 'Mentor:edit-profile' %}">
            <button>Edit Mentor Profile</button>
        </a>
        <a href="{% url 'Student:view_mentor_videos' %}">
            <button>View Uploaded Mentor Videos</button>
        </a>
        <a href="{% url 'Mentor:upload_video' %}">
            <button>Upload Video</button>
        </a>
        <!-- Add other buttons and their corresponding URLs -->
    </div>
</body>
</html>

Mentor/templates/registration.html
<!DOCTYPE html>
<html>
<head>
    <title>Mentor Registration</title>
    <!-- Add your CSS link here -->
</head>
<body>
    <h1>Mentor Registration</h1>
    <!-- Form for mentor registration -->
   
    <form method="post" action="{% url 'Mentor:mentor-registration' %}"> 
    
        {% csrf_token %}
        
        <!-- Username -->
        <label for="username">Username:</label><br>
        <input type="text" id="username" name="username" required><br><br>
        
        <!-- Mobile -->
        <label for="mobile">Mobile (Unique):</label><br>
        <input type="text" id="mobile" name="mobile" required><br><br>
        
        <!-- Full Name -->
        <label for="full_name">Full Name:</label><br>
        <input type="text" id="full_name" name="full_name" required><br><br>
        
        <!-- Email -->
        <label for="email">Email:</label><br>
        <input type="email" id="email" name="email" required><br><br>
        
        <!-- Password -->
        <label for="password">Password:</label><br>
        <input type="password" id="password" name="password" required><br><br>
        
        <!-- Gender -->
        <label for="gender">Gender:</label><br>
        <select id="gender" name="gender" required>
            <option value="M">Male</option>
            <option value="F">Female</option>
            <option value="O">Other</option>
        </select><br><br>
        
        <!-- Address -->
        <label for="address">Address:</label><br>
        <textarea id="address" name="address" required></textarea><br><br>
        
        <!-- Aadhar -->
        <label for="aadhar">Aadhar:</label><br>
        <input type="text" id="aadhar" name="aadhar" required><br><br>
        
        <!-- Pic -->
        <label for="pic">Profile Picture:</label><br>
        <input type="file" id="pic" name="pic" accept="image/*" required><br><br>
        
        <!-- Class -->
        <label for="class_field">Class:</label><br>
        <input type="text" id="class_field" name="class_field" required><br><br>
        
        <!-- Section -->
        <label for="section">Section:</label><br>
        <input type="text" id="section" name="section" required><br><br>
        
        <!-- Submit Button -->
        <input type="submit" value="Register">
    </form>

    

</body>
</html>

Mentor/templates/upload_video.html
<!DOCTYPE html>
<html>
<head>
    <title>Upload Video</title>
</head>
<body>
    <h1>Upload Video</h1>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Upload</button>
    </form>
</body>
</html>

Mentor/templates/user_details.html
<!DOCTYPE html>
<html>
<head>
    <title>User Details</title>
    <!-- Add your CSS link here -->
</head>
<body>
    <h1>User Details</h1>
    <div>
        <p><strong>Username:</strong> {{ user.username }}</p>
        <p><strong>Mobile (Unique):</strong> {{ user.mobile }}</p>
        <p><strong>Full Name:</strong> {{ user.full_name }}</p>
        <p><strong>Email:</strong> {{ user.email }}</p>
        <p><strong>Password:</strong> {{ user.password }}</p>
        <p><strong>Gender:</strong> {{ user.gender }}</p>
        <p><strong>Address:</strong> {{ user.address }}</p>
        <p><strong>Aadhar:</strong> {{ user.aadhar }}</p>
        <!-- Displaying the image (change this according to your image field) -->
        <p><strong>Profile Picture:</strong><br>
            <img src="{{ user.pic.url }}" alt="Profile Picture" height="150" width="150">
        </p>
        <p><strong>Class:</strong> {{ user.class_field }}</p>
        <p><strong>Section:</strong> {{ user.section }}</p>
        <!-- Add other user details you want to display -->
    </div>
</body>
</html>

Mentor/templates/view_videos.html
<!DOCTYPE html>
<html>
<head>
    <title>View Videos</title>
</head>
<body>
    <h1>Uploaded Videos</h1>
    {% if videos %}
        <ul>
            {% for video in videos %}
                <li>
                    <strong>{{ video.title }}</strong><br>
                    <video width="320" height="240" controls>
                        <source src="{{ video.video_file.url }}" type="video/mp4">
                        Your browser does not support the video tag.
                    </video>
                </li>
            {% endfor %}
        </ul>
    {% else %}
        <p>No videos uploaded yet.</p>
    {% endif %}
</body>
</html>