Mentor/urls.py
from django.urls import path
from . import views
from .views import MentorListCreateView, MentorDetailView, MentorRegisterView, MentorLoginView, MentorDetailsView

app_name = 'Mentor'

urlpatterns = [
    
    path('mentor/mentors/', MentorListCreateView.as_view(), name='mentor-list'),
    path('mentor/mentors/<int:pk>/', MentorDetailView.as_view(), name='mentor-detail'),
    path('mentor/register/', MentorRegisterView.as_view(), name='mentor-registration'),
    path('mentor/login/', MentorLoginView.as_view(), name='login'),
    path('mentor/user-details/', MentorDetailsView.as_view(), name='user-details'),
    path('', views.home, name='home'),
    path('mentor/edit-profile/', views.edit_profile, name='edit-profile'),
    path('mentor/upload/', views.upload_video, name='upload_video'),
    path('mentor/view-videos/', views.view_videos, name='view_videos'),
    path('mentor/mentor-dashboard/', views.mentor_dashboard, name='mentor-dashboard'),

    # path('registration/', views.mentor_registration, name='mentor-registration'),
    # path('login/', views.mentor_login, name='mentor-login'),
]

School/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.contrib.staticfiles.urls import static, staticfiles_urlpatterns
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Mentor.urls')),
    path('student/', include('Student.urls')),
    path('', views.home, name='home'),
    # path('', views.home, name='home' ),
]
urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Student/urls.py
from django.urls import path
from . import views
from .views import (
    StudentRegisterView,
    StudentLoginView,
    StudentDetailsView,
    edit_student_profile,
    view_mentor_videos,
)

app_name = 'Student' 

urlpatterns = [
    path('register/', StudentRegisterView.as_view(), name='student-registration'),
    path('login/', StudentLoginView.as_view(), name='student-login'),
    path('details/', StudentDetailsView.as_view(), name='student-details'),
    path('edit-profile/', edit_student_profile, name='edit-student-profile'),
    path('view-mentor-videos/', view_mentor_videos, name='view-mentor-videos'),
    path('student-dashboard/', views.student_dashboard, name='student-dashboard'),
    # Other paths for student-related functionalities
]

Student/models.py
from django.db import models

class Student(models.Model):
    GENDER_CHOICES = (
        ('M', 'Male'),
        ('F', 'Female'),
        ('O', 'Other'),
    )

    username = models.CharField(max_length=100)
    mobile = models.CharField(max_length=15, unique=True)
    full_name = models.CharField(max_length=255)
    email = models.EmailField()
    password = models.CharField(max_length=100)
    gender = models.CharField(max_length=1, choices=GENDER_CHOICES)
    address = models.TextField()
    aadhar = models.CharField(max_length=20)
    pic = models.ImageField(upload_to='student_pics/')
    class_field = models.CharField(max_length=50)
    section = models.CharField(max_length=10)

Student/forms.py
from django import forms
from .models import Student
# from .models import Video

class StudentEditForm(forms.ModelForm):
    class Meta:
        model = Student
        fields = ['username', 'mobile', 'full_name', 'email', 'password', 'gender', 'address', 'aadhar', 'pic', 'class_field', 'section']
        # Customize the fields as needed

# class VideoForm(forms.ModelForm):
#     class Meta:
#         model = Video
#         fields = ['title', 'video_file']

Student/views.py
from django.shortcuts import render
from rest_framework import generics, status
from rest_framework.response import Response
from rest_framework.authtoken.models import Token
from django.contrib.auth import authenticate
from django.shortcuts import render, redirect
from .models import Student
from .serializers import StudentSerializer
from Mentor.models import Video as MentorVideo
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse
from django.views import View
from .forms import StudentEditForm





class StudentListCreateView(generics.ListCreateAPIView):
    queryset = Student.objects.all()
    serializer_class = StudentSerializer

class StudentDetailView(generics.RetrieveUpdateDestroyAPIView):
    queryset = Student.objects.all()
    serializer_class = StudentSerializer


class StudentRegisterView(generics.CreateAPIView):
    queryset = Student.objects.all()
    serializer_class = StudentSerializer
 
    def get(self, request, *args, **kwargs):
        return render(request, 'student_registration.html')

    def post(self, request, *args, **kwargs):
        serializer = self.get_serializer(data=request.data)
        if serializer.is_valid():
            serializer.save()
            return Response({
                "status": status.HTTP_201_CREATED,
                "message": "Student registered successfully.",
            }, status=status.HTTP_201_CREATED)
        return Response({
            "status": status.HTTP_400_BAD_REQUEST,
            "message": serializer.errors.get('message', 'Invalid input data.'),
            "data": serializer.errors
        }, status=status.HTTP_400_BAD_REQUEST)

class StudentLoginView(View):
    def get(self, request, *args, **kwargs):
        return render(request, 'student_login.html')
 
    def post(self, request, *args, **kwargs):
        username_mobile = request.POST.get('username_mobile')
        password = request.POST.get('password')

        # Authenticate user by username or mobile number
        user = authenticate(request, username=username_mobile, password=password)
        if user is not None:
            # User authentication successful, generate token
            token, created = Token.objects.get_or_create(user=user)
            # return redirect('student-dashboard')
            return Response({'token': token.key}, status=status.HTTP_200_OK)
        else:
            # Invalid credentials
            return Response({'error': 'Invalid credentials'}, status=status.HTTP_401_UNAUTHORIZED)

class StudentDetailsView(generics.RetrieveAPIView):
    serializer_class = StudentSerializer

    def get_object(self):
        token = self.request.GET.get('token')
        if token:
            try:
                user = Token.objects.get(key=token).user
                return user
            except Token.DoesNotExist:
                return None
        return None

    def get(self, request, *args, **kwargs):
        user = self.get_object()
        if user:
            serializer = self.serializer_class(user)
            return Response(serializer.data, status=status.HTTP_200_OK)
        else:
            return Response({'error': 'Invalid token'}, status=status.HTTP_401_UNAUTHORIZED)

@login_required
def edit_student_profile(request):
    if request.method == 'POST':
        form = StudentEditForm(request.POST, instance=request.user)
        if form.is_valid():
            form.save()
            return redirect('student-details')  # Redirect to the student details page after successful update
    else:
        form = StudentEditForm(instance=request.user)
    
    return render(request, 'edit_student_profile.html', {'form': form})

@login_required
def view_mentor_videos(request):
    mentor_videos = MentorVideo.objects.all()
    return render(request, 'view_mentor_videos.html', {'mentor_videos': mentor_videos})

@login_required
def student_dashboard(request):
    return render(request, 'student_dashboard.html')

Student/templates/edit_student_profile.html
<!DOCTYPE html>
<html>
<head>
    <title>Edit Student Profile</title>
    <!-- Add your CSS link here -->
</head>
<body>
    <h1>Edit Student Profile</h1>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Save Changes">
    </form>
</body>
</html>

Student/templates/student_dashboard.html
<!DOCTYPE html>
<html>
<head>
    <title>Student Dashboard</title>
    <!-- Add your CSS link here -->
</head>
<body>
    <h1>Welcome to Student Dashboard</h1>
    <div>
        <p>Click on the buttons below to navigate:</p>
        <a href="{% url 'Student:user-details' %}">
            <button>Student Details</button>
        </a>
        <a href="{% url 'Student:edit-student-profile' %}">
            <button>Edit Student Profile</button>
        </a>
        <a href="{% url 'Mentor:view_videos' %}">
            <button>View Mentor Videos</button>
        </a>
        <!-- Add other buttons and their corresponding URLs -->
    </div>
</body>
</html>

Student/templates/student_login.html
<!DOCTYPE html>
<html>
<head>
    <title>Student Login</title>
    <!-- Add your CSS link here -->
</head>
<body>
    <h1>Student Login</h1>
    <!-- Form for student login -->
    <form method="post" action="{% url 'Student:student-login' %}">
        {% csrf_token %}
        
        <!-- Username or Mobile -->
        <label for="username_mobile">Username/Mobile:</label><br>
        <input type="text" id="username_mobile" name="username_mobile" required><br><br>
        
        <!-- Password -->
        <label for="password">Password:</label><br>
        <input type="password" id="password" name="password" required><br><br>
        
        <!-- Submit Button -->
        <input type="submit" value="Login">
    </form>
</body>
</html>

Student/templates/student_registration.html
<!DOCTYPE html>
<html>
<head>
    <title>Student Registration</title>
    <!-- Add your CSS link here -->
</head>
<body>
    <h1>Student Registration</h1>
    <!-- Form for Student registration -->
   
    <form method="post" action="{% url 'Student:student-registration' %}"> 
    
        {% csrf_token %}
        
        <!-- Username -->
        <label for="username">Username:</label><br>
        <input type="text" id="username" name="username" required><br><br>
        
        <!-- Mobile -->
        <label for="mobile">Mobile (Unique):</label><br>
        <input type="text" id="mobile" name="mobile" required><br><br>
        
        <!-- Full Name -->
        <label for="full_name">Full Name:</label><br>
        <input type="text" id="full_name" name="full_name" required><br><br>
        
        <!-- Email -->
        <label for="email">Email:</label><br>
        <input type="email" id="email" name="email" required><br><br>
        
        <!-- Password -->
        <label for="password">Password:</label><br>
        <input type="password" id="password" name="password" required><br><br>
        
        <!-- Gender -->
        <label for="gender">Gender:</label><br>
        <select id="gender" name="gender" required>
            <option value="M">Male</option>
            <option value="F">Female</option>
            <option value="O">Other</option>
        </select><br><br>
        
        <!-- Address -->
        <label for="address">Address:</label><br>
        <textarea id="address" name="address" required></textarea><br><br>
        
        <!-- Aadhar -->
        <label for="aadhar">Aadhar:</label><br>
        <input type="text" id="aadhar" name="aadhar" required><br><br>
        
        <!-- Pic -->
        <label for="pic">Profile Picture:</label><br>
        <input type="file" id="pic" name="pic" accept="image/*" required><br><br>
        
        <!-- Class -->
        <label for="class_field">Class:</label><br>
        <input type="text" id="class_field" name="class_field" required><br><br>
        
        <!-- Section -->
        <label for="section">Section:</label><br>
        <input type="text" id="section" name="section" required><br><br>
        
        <!-- Submit Button -->
        <input type="submit" value="Register">
    </form>

    

</body>
</html>

Student/templates/view_mentor_videos.html
<!DOCTYPE html>
<html>
<head>
    <title>Mentor's Uploaded Videos</title>
</head>
<body>
    <h1>Mentor's Uploaded Videos</h1>
    {% if videos %}
        <ul>
            {% for video in videos %}
                <li>
                    <strong>{{ video.title }}</strong><br>
                    <video width="320" height="240" controls>
                        <source src="{{ video.video_file.url }}" type="video/mp4">
                        Your browser does not support the video tag.
                    </video>
                </li>
            {% endfor %}
        </ul>
    {% else %}
        <p>No mentor videos uploaded yet.</p>
    {% endif %}
</body>
</html>